const PARTY = {
  title: "Andrew's Bachelor Party",
  dateDisplay: "Sunday, July 5, 2026",
  dateISO: "2026-07-05T11:00:00-07:00",
  guestCount: 6,
  payingGuestCount: 5,
  payment: {
    venmo: { handle: "@GabrielMagallanes", username: "GabrielMagallanes" }
  },
  schedule: [
    {
      id: "mass",
      type: "event",
      icon: "⛪",
      title: "Mass",
      venue: "St. Therese of Lisieux Catholic Church",
      location: "Alhambra, CA",
      city: "Alhambra",
      lat: 34.1057856,
      lng: -118.1190234,
      start: "11:00",
      end: "12:30",
      status: "tentative",
      cost: 0,
      notes: "Also the wedding venue."
    },
    {
      id: "drive1",
      type: "travel",
      icon: "🚗",
      title: "Drive to Jersey Mike's",
      duration: "~25 min",
      notes: "Alhambra to West Covina, ~21 min with no traffic."
    },
    {
      id: "lunch",
      type: "event",
      icon: "🥪",
      title: "Lunch",
      venue: "Jersey Mike's Subs",
      location: "2200 S Azusa Ave Suite 103, West Covina, CA",
      city: "West Covina",
      lat: 34.0510195,
      lng: -117.9080899,
      start: "13:00",
      end: "14:00",
      status: "tentative",
      cost: 15,
      notes: "Quick and simple — keeps the first half of the day moving. Right by Laserland."
    },
    {
      id: "drive2",
      type: "travel",
      icon: "🚶",
      title: "Walk to Laserland",
      duration: "~5 min",
      notes: "Right next door."
    },
    {
      id: "lasertag",
      type: "event",
      icon: "🔫",
      title: "Laser Tag",
      venue: "Laserland",
      location: "2340 S Azusa Ave, West Covina, CA",
      city: "West Covina",
      lat: 34.0341065,
      lng: -117.9131763,
      start: "14:00",
      end: "15:00",
      status: "pending",
      cost: 25,
      notes: "Booking tomorrow — can't reserve more than 14 days out. 1-hour session: the party package (3 games + private room) is only offered for bigger groups and gets pricey at our size, so we're doing the standard 1-hour walk-in rate instead."
    },
    {
      id: "drive3",
      type: "travel",
      icon: "🚗",
      title: "Drive to Klatch Coffee",
      duration: "~10 min",
      notes: "Same city — West Covina location, not the Rancho one."
    },
    {
      id: "coffee",
      type: "event",
      icon: "☕",
      title: "Coffee",
      venue: "Klatch Coffee Roasting",
      location: "2630 E Workman Ave, West Covina, CA",
      city: "West Covina",
      lat: 34.0746154,
      lng: -117.8887399,
      start: "15:10",
      end: "16:00",
      status: "tentative",
      cost: 8,
      notes: "One of Andrew's favorite coffee spots — a real specialty roastery. Last stop before we head to Rancho."
    },
    {
      id: "drive4",
      type: "travel",
      icon: "🚗",
      title: "Drive to Rancho Cucamonga",
      duration: "~35 min",
      notes: "West Covina to Rancho Cucamonga, ~30 min with no traffic. Second phase of the night starts here."
    },
    {
      id: "game",
      type: "event",
      icon: "🎮",
      title: "Immersive Gamebox",
      venue: "Immersive Gamebox",
      location: "Victoria Gardens, Rancho Cucamonga, CA",
      city: "Rancho Cucamonga",
      lat: 34.1115417,
      lng: -117.5325812,
      start: "17:00",
      end: "18:00",
      status: "pending",
      cost: 35,
      notes: "Standard 60-min mixed-reality game, no add-on."
    },
    {
      id: "walk1",
      type: "travel",
      icon: "🚶",
      title: "Walk to Fogo de Chão",
      duration: "~5 min",
      notes: "Same shopping complex."
    },
    {
      id: "dinner",
      type: "event",
      icon: "🍖",
      title: "Dinner",
      venue: "Fogo de Chão",
      location: "12240 Foothill Blvd, Rancho Cucamonga, CA",
      city: "Rancho Cucamonga",
      lat: 34.1067929,
      lng: -117.5385478,
      start: "18:30",
      end: "20:00",
      status: "confirmed",
      cost: 75,
      notes: "Table reserved for 6:30pm."
    },
    {
      id: "drive5",
      type: "travel",
      icon: "🚗",
      title: "Drive to La Verne",
      duration: "~20 min",
      notes: "~17 min with no traffic."
    },
    {
      id: "house",
      type: "event",
      icon: "🃏",
      title: "Poker, Cigars & Guitars",
      venue: "Private House",
      location: "📍 Address sent separately",
      city: "La Verne",
      lat: 34.1008426,
      lng: -117.7678355,
      mapApprox: true,
      start: "20:20",
      end: "23:00",
      status: "tentative",
      cost: 0,
      notes: "Free. Side bets at the poker table are fair game if you're into it — no obligation though.",
      noDirections: true
    }
  ]
};
